namespace: tp7-kustomize

  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
images:
- name: ghcr.io/<VOTRE_USER_GITHUB>/spring-petclinic
  newName: ghcr.io/<VOTRE_USER_GITHUB>/spring-petclinic
  newTag: 4.0.1
- name: spring-petclinic
  newName: ghcr.io/Chaveex/spring-petclinic
  newTag: ebc235e6c13dd4b0cb4ee2716eb19c81dbbb2a45



# Référencer la baseline (réutiliser tous les manifests de base/)
resources:
- ../../base

# Appliquer les patches (modifications)
  # Type 1 : JSON Patch (replicas.yaml) - syntaxe très spécifique, ex: /spec/replicas
patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: clinic-deploy
- path: patch-routine.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
